# Do NOT update manually; changes here will be overwritten by Copier
_commit: v1.14.0
_src_path: https://github.com/OCA/oca-addons-repo-template.git
ci: GitHub
dependency_installation_mode: PIP
generate_requirements_txt: true
github_check_license: false
github_ci_extra_env: {}
github_enable_codecov: true
github_enable_makepot: true
github_enable_stale_action: true
github_enforce_dev_status_compatibility: false
include_wkhtmltopdf: true
odoo_version: 14.0
org_name: Cetmix bootcamp
org_slug: volodiay616
rebel_module_groups: []
repo_description: Bootcamp test tasks
repo_name: Bootcamp tasks
repo_slug: bootcamp
repo_website: https://github.com/volodiay616/bootcamp
travis_apt_packages: []
travis_apt_sources: []

